name: Check for Security Advisories

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - '**/deny.toml'
  push:
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - '**/deny.toml'
    branches:
      - main
  schedule:
    - cron: '57 1 * * *'

jobs:
  advisories:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run cargo deny
        uses: EmbarkStudios/cargo-deny-action@3fd3802e88374d3fe9159b834c7714ec57d6c979 # v2.0.15
        with:
            command: check advisories